// Database models
export { default as Student } from './Student.model'
export { default as User, UserRole } from './User.model'
export { default as Teacher } from './Teacher.model'
export { default as Class } from './Class.model'
export { default as Subject } from './Subject.model'
export type { IStudent } from './Student.model'
export type { IUser } from './User.model'
export type { ITeacher } from './Teacher.model'
export type { IClass } from './Class.model'
export type { ISubject } from './Subject.model'